apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: security-headers
  namespace: envoy-gateway-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-public
      sectionName: https
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-private
      sectionName: https
  headers:
    lateResponseHeaders:
      set:
        - name: Strict-Transport-Security
          value: max-age=31536000; includeSubDomains; preload
        - name: Referrer-Policy
          value: same-origin, strict-origin-when-cross-origin
        - name: X-Content-Type-Options
          value: nosniff
        - name: X-Frame-Options
          value: SAMEORIGIN
