apiVersion: v1
kind: Secret
metadata:
  name: borgbase-ssh
  namespace: minecraft
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: default/borgbase-ssh
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: borgmatic
  namespace: minecraft
spec:
  chart:
    spec:
      chart: borgmatic
      version: 0.10.1
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: gabe565
  interval: 1h
  driftDetection:
    mode: enabled
  values:
    controller:
      type: cronjob
      cronjob:
        schedule: 0 3 * * *
        concurrencyPolicy: Replace
        ttlSecondsAfterFinished: 3600
    affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: minecraft
    tolerations:
      - key: gabe565.com/gpu
        operator: Equal
        value: nvidia
        effect: NoSchedule
    podLabels:
      policy.gabe565.com/egress-healthchecks: "true"
      policy.gabe565.com/egress-namespace: "true"
      policy.gabe565.com/egress-world: "true"
    env:
      TZ: America/Chicago
      BORG_PASSPHRASE: ${borg_passphrase}
      PING_KEY:
        secretKeyRef:
          name: healthchecks-ping-key
          key: key
    persistence:
      data:
        enabled: true
        storageClass: nfs-client
        size: 100Mi
        accessMode: ReadWriteMany
      ssh:
        enabled: true
        type: secret
        name: borgbase-ssh
      minecraft-data:
        enabled: true
        existingClaim: minecraft
    configMaps:
      config:
        data:
          # language=yaml
          config.yaml: |
            repositories:
              - path: ${borg_repo}
                label: borgbase
            source_directories:
              - /minecraft-data
            exclude_patterns:
              - /minecraft-data/*.jar
              - /minecraft-data/.cache
              - /minecraft-data/bluemap
              - /minecraft-data/cache
              - /minecraft-data/libraries
              - /minecraft-data/logs
              - /minecraft-data/plugins/*.jar
              - /minecraft-data/versions
            archive_name_format: "minecraft-{now:%Y-%m-%d-%H%M%S}"
            ssh_command: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o LogLevel=ERROR
            retries: 2
            retry_wait: 10
            keep_hourly: 24
            keep_daily: 90
            keep_weekly: 24
            keep_monthly: 24
            keep_yearly: 20
            check_last: 3
            healthchecks:
              ping_url: http://healthchecks.healthchecks:8000/ping/${healthchecks_uuid}
