apiVersion: v1
kind: Secret
metadata:
  name: ${app_certificate_name}
  namespace: minio
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: cert-manager/${app_certificate_name}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${s3_url}
  namespace: minio
spec:
  secretName: ${s3_certificate_name}
  dnsNames:
    - ${s3_url}
    - "*.${s3_url}"
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-envoy-gateway-tls
  namespace: minio
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: envoy-gateway-system
  to:
    - group: ""
      kind: Secret
      name: ${s3_certificate_name}
