apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app
  namespace: minecraft
spec:
  interval: 1h
  targetNamespace: minecraft
  path: ./kubernetes/gabernetes/apps/minecraft/resources
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: home-ops
  postBuild:
    substituteFrom:
      - kind: Secret
        name: app-vars
