apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: ingress-envoy-private
spec:
  endpointSelector:
    matchLabels:
      policy.gabe565.com/ingress-envoy-private: "true"
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: envoy-gateway-system
            app.kubernetes.io/name: envoy
            app.kubernetes.io/managed-by: envoy-gateway
            app.kubernetes.io/component: proxy
            gateway.envoyproxy.io/owning-gateway-name: envoy-private
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: ingress-envoy-private
  namespace: envoy-gateway-system
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: envoy
      app.kubernetes.io/managed-by: envoy-gateway
      app.kubernetes.io/component: proxy
      gateway.envoyproxy.io/owning-gateway-name: envoy-private
  egress:
    - toEndpoints:
        - matchLabels:
            policy.gabe565.com/ingress-envoy-private: "true"
          matchExpressions:
            - key: io.kubernetes.pod.namespace
              operator: Exists
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: egress-envoy-private
spec:
  endpointSelector:
    matchLabels:
      policy.gabe565.com/egress-envoy-private: "true"
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: envoy-gateway-system
            app.kubernetes.io/name: envoy
            app.kubernetes.io/managed-by: envoy-gateway
            app.kubernetes.io/component: proxy
            gateway.envoyproxy.io/owning-gateway-name: envoy-private
    - toCIDRSet:
        - cidr: 192.168.1.228/32
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: egress-envoy-private
  namespace: envoy-gateway-system
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: envoy
      app.kubernetes.io/managed-by: envoy-gateway
      app.kubernetes.io/component: proxy
      gateway.envoyproxy.io/owning-gateway-name: envoy-private
  ingress:
    - fromEndpoints:
        - matchLabels:
            policy.gabe565.com/egress-envoy-private: "true"
          matchExpressions:
            - key: io.kubernetes.pod.namespace
              operator: Exists
