apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mqtt-tls
  namespace: home-assistant
spec:
  secretName: mqtt-tls
  commonName: homeassistant
  duration: 87600h # 10 years
  renewBefore: 720h # 30 days
  issuerRef:
    kind: ClusterIssuer
    name: mqtt
