apiVersion: v1
kind: Secret
metadata:
  name: ${old_certificate_name}
  namespace: home-assistant
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: cert-manager/${old_certificate_name}
---
apiVersion: v1
kind: Secret
metadata:
  name: ${certificate_name}
  namespace: home-assistant
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: cert-manager/${certificate_name}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mqtt-tls
  namespace: home-assistant
spec:
  secretName: mqtt-tls
  commonName: homeassistant
  duration: 87600h # 10 years
  renewBefore: 720h # 30 days
  issuerRef:
    kind: ClusterIssuer
    name: mqtt
