apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: longhorn-system
  namespace: longhorn-system
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - {}
    - fromEntities:
        - host
    - fromEntities:
        - remote-node
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: envoy-gateway-system
            app.kubernetes.io/name: envoy
            app.kubernetes.io/managed-by: envoy-gateway
            app.kubernetes.io/component: proxy
            gateway.envoyproxy.io/owning-gateway-name: envoy-public
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: prometheus
  egress:
    - toEndpoints:
        - {}
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
    - toEntities:
        - host
    - toEntities:
        - remote-node
