apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  interval: 1h
  type: oci
  url: oci://registry.k8s.io/nfd/charts
