apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mqtt-tls
  namespace: zigbee2mqtt
spec:
  secretName: mqtt-tls
  commonName: zigbee2mqtt
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  issuerRef:
    kind: ClusterIssuer
    name: mqtt
